### ISSUE TITLE
Not working on osx 10.11.6

### ISSUE THREAD

**Issue by cmpscabral** [laander/dai#1]
Is there a minimum osx version?
thanks

**Comment by laander** [comment]
Good question. Does it open at all? If not, does it provide an error message?

I assume Tauri (used for app packaging) has a minimum required OS version, but no mention of it in the docs.

**Comment by laander** [comment]
I don't think we can expect support for OSX 10.11.6 anytime soon, sorry 🙂 (for good reasons tho)

https://twitter.com/TauriApps/status/1443306494104068098?s=19

**Comment by cmpscabral** [comment]
No, it doesn't open at all. Shows dialog saying there's a problem, report to Apple, etc...
Thanks anyway!
